### PR TITLE
Fix crash with minified functions

### PR DESCRIPTION
**Pull request by danieleds**
This is an example of a valid minified function that doesn't work with the regex in toFunction:

    function profileModelWorkerRunner(){var Moment=eval("require")("moment-timezone");self.onmessage=function(event){var profileModelClass=eval("require")(event.data.profileModelPath).default,profileModelWorker=new profileModelClass(Moment,event.data.timezone),params=event.data.params;var result=profileModelWorker.check(params);postMessage(result)}}

I've replaced that code with an eval, which is safer than parsing JS code (which is not a context-free grammar) with regular expressions.

### CODE REVIEW

**Comment by danieleds** [comment]
@avoidwork  ehm sorry, why did you close this?

**Comment by avoidwork** [comment]
@danieleds your example is effectively sending a function that behaves like a closure, and the notion that 'eval' is better than 'new Function()' is odd; they both 'eval()' but 1 is insuring a valid function.

**Comment by avoidwork** [comment]
@danieleds that is to say, if you want to do something like that don't pass a function but a path to that script on disk.

**Comment by danieleds** [comment]
@avoidwork thanks, could you elaborate? I mean, where is the issue located in my example?

Btw, I never said that new Function() is bad, I was saying that you cannot safely parse a non-context-free language with regular expressions. Because math.

**Comment by avoidwork** [comment]
@danieleds sure, so 2 things... firstly it only fails eval to a `Function` due to you using `eval("require")` which isn't required; secondly the regex is problematic only because it's a 1 liner, so if you wanted to fix that then fix the regex.

**Comment by avoidwork** [comment]
I gotta admit, your notion of string manipulation not being valid "because math" is really off the mark, because math.

**Comment by danieleds** [comment]
@avoidwork 

> firstly it only fails eval to a Function due to you using eval("require") which isn't required

It is required in my code, because of a webpack exclusion. Anyway, even removing the eval it it still doesn't work and fails with the same message: `SyntaxError: Unexpected token }`.
Of course if I paste it in node it parses just fine, like before.

> secondly the regex is problematic only because it's a 1 liner, so if you wanted to fix that then fix the regex.

That's what I wanted to hear. Unfortunately, I don't understand where I should put the newline, since it keeps failing. Could you provide an example, so that we can fix the regex?

> I gotta admit, your notion of string manipulation not being valid "because math" is really off the mark, because math.

You might want to learn some notion about parsing, here's a few links ("the math"):
https://en.wikipedia.org/wiki/Regular_language
https://en.wikipedia.org/wiki/Context-free_grammar

**Comment by avoidwork** [comment]
@danieleds i don't support webpack, and never will; your webpack problems are yours. as for the trickiness of the regex method, yes there are pitfalls because it can't work for every possible input. i don't give a fuck about that... ¯\_(ツ)_/¯

guess what else doesn't work.. arrow functions. gfr = 0. all the examples are declared functions; not expressions, not webpacked shit, or minified... because minification makes _zero sense on the server_.

**Comment by avoidwork** [comment]
screen shot 2017-09-14 at 11 33 04 am

as already mentioned, the minification isn't supported... so it's not a real problem to solve. just don't do it.

**Comment by danieleds** [comment]
> i don't support webpack, and never will; your webpack problems are yours.

You don't read. This has nothing to do with webpack, as I showed you. You can use a standard require and the problem is still there

> as for the trickiness of the regex method, yes there are pitfalls because it can't work for every possible input. i don't give a fuck about that...  ¯_(ツ)_/¯

Are you serious? This is not a problem related to minification, this is an issue which could come up with *any* function, and you don't give a fuck?

> all the examples are declared functions; not expressions, not webpacked shit, or minified

I think you got some issues and you need some counseling. 

> the minification isn't supported

This sentence doesn't mean anything. Minification isn't something you support or not... This is valid javascript and it MUST work. Stop.

Look, I don't really give a fuck if you merge this or not, I'm happy with my fork, where it is already fixed. I was just trying to help another developer. Will you end up merging this in silence after a few months, like [last time](https://github.com/avoidwork/tiny-worker/issues/8)?  
Well, at least you can't complain I didn't send you a PR...

**Comment by avoidwork** [comment]
did you even look at the screenshot; the problem only exists based on the form of the function you passed in.

that pr* was hardly merged in silence; 3 strike rule as explained. find 2 other people that need 1 lined function support and it can land.

**Comment by avoidwork** [comment]
`I think you got some issues and you need some counseling.`

you mistake disinterest with issues. you're generating noise for my work day for problem you created, and can uncreate. fuck off.

**Comment by danieleds** [comment]
Ok ok, your repo your rules, I guess.

Also, now I get why most Adobe software has so many bugs and security issues.

**Comment by avoidwork** [comment]
you're on a roll buddy; chances of anything you want to do landing is approaching positive zero.

**Comment by avoidwork** [comment]
I'm making you a collaborator so you can do whatever you feel this lib needs. I'm a bottleneck for it atm.

**Comment by danieleds** [comment]
Thanks. I'm very familiar with that situation myself

**Pull request merged**
